### ISSUE TITLE
AppService missing

### ISSUE THREAD

**Issue by allanmc** [rogerpadilla/angular2-minimalist-starter#24]
It looks like you forgot to add the needed files for AppService introduced in 01a9b59022a5fcc25eaf1f0b8dd06dabd50e83e2.

```
ERROR in ./src/app/app.component.ts
(3,28): error TS2307: Cannot find module './app.service'.

ERROR in ./src/main.ts
(6,28): error TS2307: Cannot find module './app/app.service'.
```

**Comment by rogerpadilla** [comment]
Fixed, thanks!
